# Generated by Django 2.2.4 on 2019-08-09 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('question', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
